theme: minima
title: Traccar Performance Analysis
description: Performance analysis and documentation for hosting Traccar GPS tracking servers on DigitalOcean droplets

markdown: kramdown
highlighter: rouge

plugins:
  - jekyll-feed
  - jekyll-sitemap

exclude:
  - README.md